### ISSUE TITLE
BlueLake博客主题的详细配置 | 秋过冬漫长

### ISSUE THREAD

**Issue by chaooo** [chaooo/BlogComments#2]
https://chaooo.github.io/2016/12/29/bluelake.html
https://chaoo.gitee.io/2016/12/29/bluelake.html
 郑超的个人博客，Charles·Zheng's blog.

**Comment by chenkuna** [comment]
右方目录、分类、标签在哪配置啊~~~

**Comment by chenkuna** [comment]
右方目录、分类、标签在哪配置啊~~~

**Comment by chaooo** [comment]
> @chenkuna
> 右方目录、分类、标签在哪配置啊~~~

在文章头部Front-Matter中配置，相见[Hexo文档:Front-matter](https://hexo.io/zh-cn/docs/front-matter#%E5%88%86%E7%B1%BB%E5%92%8C%E6%A0%87%E7%AD%BE)

**Comment by 841809077** [comment]
您好，我重新配置了bluelake主题配置，想着弄下我的gitalk评论，但是现在出现了：
- - - - - - - - - - - - - - - - - 
未找到相关的 Issues 进行评论

请联系 @841809077 初始化创建

使用 GitHub 登录
- - - - - - - - - - - - - - - - - 
配置详情：
gitalk:
    enable: true
    owner: 841809077
    repo: 841809077.github.io
    client_id: 7ff67---------07324aa
    client_secret: f1312asdd4d73----------aeb23423424099d
    admin: 841809077
    language: zh-CN
    pagerDirection: last
我的博客地址是：https://841809077.github.io，博客仓库是：https://github.com/841809077/841809077.github.io，请问还有哪里没有配置吗？

**Comment by edxuanlen** [comment]
谢谢

**Comment by 2dragon** [comment]
为什么我配置完成放在github上没有主题的显示，只有单纯的文字？

**Comment by chaooo** [comment]
> @2dragon
> 为什么我配置完成放在github上没有主题的显示，只有单纯的文字？
> 

检查部署时又没报错，及报错原因

**Comment by shareEnjoy** [comment]
前辈，主题config里的这个是干嘛的啊？
# MathJax Support

**Comment by Sui-Yue** [comment]
为什么我的评论功能显示Error: Not Found.

**Comment by Sui-Yue** [comment]
亲，求救

**Comment by Sui-Yue** [comment]
搞定了，是我repo没弄好

**Comment by Sui-Yue** [comment]
为何我的原文链接是这样的-http://yoursite.com/2019/10/29/欢迎来到碎月の小屋/
而不是像你一样的-http://chaooo.github.io/article/20161229.html

**Comment by bozaigao** [comment]
评论怎么显示?

**Comment by chaooo** [comment]
> @suiyuebaobao
> 为何我的原文链接是这样的-http://yoursite.com/2019/10/29/欢迎来到碎月の小屋/
> 而不是像你一样的-http://chaooo.github.io/article/20161229.html

这个是自己配置的，默认是：
```permalink: :year/:month/:day/:title.html```
我配置的是：
```permalink: article/:year:month:day.html```
但这有个不好的地方就是这是拼接的年月日，就是一天内发布两篇文章可能有冲突，
你也可以查询相关hexo文档自定义配置。

**Comment by ParanoidBarnett** [comment]
## 博主，你好，喜欢这样的风格博客。

这2天在学习搭建这个，如果不进行分支相关的操作（即仅用hexo的方法上传静态文件到master），我没什么大问题。

博主关于master分支用于托管生成的静态文件，建一个develop分支用于托管后台文件这样做法，很不错，想学习一下，但我照着教程操作过程中一直出现同步问题，后面我仔细看了一下，有关hexo这个主题的安装配置教程有2篇，一个有develop分支，一个没有，教程中有些命令的操作路径可能不一样，我是个git和hexo的初学者，相关概念或是命令理解很浅薄，这使得我在照着2篇教程学习clone和push分支相关时一直不成功，还在探索中……

感谢你的教程，虽然磕磕碰碰，但解决过程也增加学习理解

建议博主抽空更新整理一下2篇教程，使之统一化，便于后来者（应该还是有像我这样的初学者）学习使用

**Comment by chaooo** [comment]
> @ParanoidBarnett

目前没有时间弄哦，建议有时间的话你可以系统的学习以下git，对今后工作也是有帮助的，你可以在你博客发布的仓库建一个分支管理源代码，并将其设为默认分支，比如我的默认分支为blog-files放源码，master用于发布。建好后可用命令`git clone -b blog-files 仓库地址`拉取该分支到本地。详细可自己搜索看看其他教程。

**Comment by jinqiansheng** [comment]
> @suiyuebaobao
> 搞定了，是我repo没弄好
> 

大佬，repo设什么啊？

**Comment by jinqiansheng** [comment]
我出现了个问题，报错信息如下，我之前就出现了这个问题，然后我把这一行删除了 = =!。后来代码块一直不能渲染，我以为因为删除这个出现的问题，博主能看下什么问题吗？

``` java
Unhandled rejection TypeError: F:\hexo\blog\themes\BlueLake\layout\base.jade:39
    37|     link(rel='apple-touch-icon-precomposed', href=url_for('apple-touch-icon.png'))
    38|     if config.feed
  > 39|       link(rel='alternate', type=feed_type, href=url_for(config.feed.path))
    40|     if theme.comment.gitalk.enable
    41|       link(rel='stylesheet', type='text/css', href="https://unpkg.com/gitalk/dist/gitalk.css?v=" + theme.version)
    42|     block title

path.startsWith is not a function
    at Object.urlForHelper (F:\hexo\blog\node_modules\hexo-util\lib\url_for.js:16:31)
    at Object.module.exports (F:\hexo\blog\node_modules\hexo\lib\plugins\helper\url_for.js:6:18)
    at eval (eval at exports.compile (F:\hexo\blog\node_modules\_jade@1.11.0@jade\lib\index.js:218:8), <anonymous>:363:102)
    at eval (eval at exports.compile (F:\hexo\blog\node_modules\_jade@1.11.0@jade\lib\index.js:218:8), <anonymous>:1783:22)
    at res (F:\hexo\blog\node_modules\_jade@1.11.0@jade\lib\index.js:219:38)

```

**Comment by chaooo** [comment]
> @jinqiansheng
不建议删代码，目测是没有添加RSS造成的

**Comment by DustReliant** [comment]
ERROR F:\hexo\hexo\themes\BlueLake\layout\post.jade:14
    12|         +comment-count(page.path)
    13|       p
  > 14|         span.date= page.date.format(theme.date_formats.post)
    15|         if page.categories.length > 0
    16|           span
    17|             for category in page.categories.toArray()

Cannot read property 'post' of undefined
TypeError: F:\hexo\hexo\themes\BlueLake\layout\post.jade:14
    12|         +comment-count(page.path)
    13|       p
  > 14|         span.date= page.date.format(theme.date_formats.post)
    15|         if page.categories.length > 0
    16|           span
    17|             for category in page.categories.toArray()

Cannot read property 'post' of undefined
    at eval (eval at exports.compile (F:\hexo\hexo\node_modules\jade\lib\index.js:218:8), <anonymous>:713:108)
    at eval (eval at exports.compile (F:\hexo\hexo\node_modules\jade\lib\index.js:218:8), <anonymous>:2582:22)
    at res (F:\hexo\hexo\node_modules\jade\lib\index.js:219:38)
    at Theme._View.View._compiled (F:\hexo\hexo\node_modules\hexo\lib\theme\view.js:123:48)
    at Theme._View.View.View.render (F:\hexo\hexo\node_modules\hexo\lib\theme\view.js:29:15)
    at F:\hexo\hexo\node_modules\hexo\lib\hexo\index.js:349:21
    at tryCatcher (F:\hexo\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at F:\hexo\hexo\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (F:\hexo\hexo\node_modules\hexo\lib\hexo\router.js:123:3)
    at RouteStream.Readable.read (_stream_readable.js:491:10)



这个报错这怎么回事？

**Comment by hezhenyun** [comment]
> @jinqiansheng
> > @suiyuebaobao
> > 搞定了，是我repo没弄好
> > 
> 
> 大佬，repo设什么啊？

>repo怎么设？？为什么按照博主的设一直不对

**Comment by ParanoidBarnett** [comment]
发表的博文中markdown格式的斜体不能生效，大家有这个问题吗？

**Comment by actadd** [comment]
> @hezhenyun
> > @jinqiansheng
> > > @suiyuebaobao
> > > 搞定了，是我repo没弄好
> > > 
> > 
> > 大佬，repo设什么啊？
> 
> >repo怎么设？？为什么按照博主的设一直不对

__repo后面接仓库名称，如：repo: MyBlogComment__

**Comment by gytBibble** [comment]
博主你好，我能问一下页面底部的备案号是在哪个文件添加的

**Comment by dute7liang** [comment]
> @gytBibble
> 博主你好，我能问一下页面底部的备案号是在哪个文件添加的

同问。。

**Comment by dute7liang** [comment]
> @gytBibble
> 博主你好，我能问一下页面底部的备案号是在哪个文件添加的

我找到了 blog/themes/BlueLake/layout/_partial/footer.jade 这里加备案号。。

**Comment by fullstackpeng** [comment]
博主！我的博客已经发布在github上，但是站点图标为什么不显示？

**Comment by Mayaguo** [comment]
完美！ 谢谢博主 https://gmaya.top/

**Comment by Malcolm-888** [comment]
那么好的主题竟然那么少人下载.

**Comment by yzdzh** [comment]
你好，问下文章详细页的日期是怎么设置成YYYY-DD-MM这种格式的？

**Comment by DustReliant** [comment]
你好，我实在主题的配置文件里面设置的。里面有设置日期的格式，详细页面你改成你想要的格式即可。------------------ 原始邮件 ------------------
发件人: "helloWorld"<notifications@github.com>
发送时间: 2020年3月11日(星期三) 凌晨0:21
收件人: "chaooo/BlogComments"<BlogComments@noreply.github.com>;
抄送: "依尘"<2297024398@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [chaooo/BlogComments] 【Hexo博客折腾】BlueLake博客主题的详细配置 | 秋过冬漫长 (#2)



你好，问下文章详细页的日期是怎么设置成YYYY-DD-MM这种格式的？
 
&mdash;

**Comment by yzdzh** [comment]
可以了，谢谢，我一直在根目录的_config.yml改配置，忘记主题里面也有个配置文件，刚刚一改果然可以了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"依尘"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月11日(星期三) 凌晨0:36
收件人:&nbsp;"chaooo/BlogComments"<BlogComments@noreply.github.com&gt;;
抄送:&nbsp;"王壮林"<842866986@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [chaooo/BlogComments] 【Hexo博客折腾】BlueLake博客主题的详细配置 | 秋过冬漫长 (#2)



你好，我实在主题的配置文件里面设置的。里面有设置日期的格式，详细页面你改成你想要的格式即可。------------------ 原始邮件 ------------------ 
 发件人: "helloWorld"<notifications@github.com&gt; 
 发送时间: 2020年3月11日(星期三) 凌晨0:21 
 收件人: "chaooo/BlogComments"<BlogComments@noreply.github.com&gt;; 
 抄送: "依尘"<2297024398@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 
 主题: Re: [chaooo/BlogComments] 【Hexo博客折腾】BlueLake博客主题的详细配置 | 秋过冬漫长 (#2) 
 
 
 
 你好，问下文章详细页的日期是怎么设置成YYYY-DD-MM这种格式的？ 
   
 &amp;mdash;

**Comment by yzdzh** [comment]
顺便问下你平时是用什么写文章的，有什么图形化工具编辑文章的，还有就是平时你新插入的图片都是存到哪的，我不想用别人的图床但是不用的话本地以后文章多了可能也不太好。。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"我自己的邮箱"<842866986@qq.com&gt;;
发送时间:&nbsp;2020年3月11日(星期三) 中午1:21
收件人:&nbsp;"chaooo/BlogComments"<reply@reply.github.com&gt;;

主题:&nbsp;回复： [chaooo/BlogComments] 【Hexo博客折腾】BlueLake博客主题的详细配置 | 秋过冬漫长 (#2)



可以了，谢谢，我一直在根目录的_config.yml改配置，忘记主题里面也有个配置文件，刚刚一改果然可以了。




------------------ 原始邮件 ------------------
发件人:&nbsp;"依尘"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月11日(星期三) 凌晨0:36
收件人:&nbsp;"chaooo/BlogComments"<BlogComments@noreply.github.com&gt;;
抄送:&nbsp;"王壮林"<842866986@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [chaooo/BlogComments] 【Hexo博客折腾】BlueLake博客主题的详细配置 | 秋过冬漫长 (#2)



你好，我实在主题的配置文件里面设置的。里面有设置日期的格式，详细页面你改成你想要的格式即可。------------------ 原始邮件 ------------------ 
 发件人: "helloWorld"<notifications@github.com&gt; 
 发送时间: 2020年3月11日(星期三) 凌晨0:21 
 收件人: "chaooo/BlogComments"<BlogComments@noreply.github.com&gt;; 
 抄送: "依尘"<2297024398@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 
 主题: Re: [chaooo/BlogComments] 【Hexo博客折腾】BlueLake博客主题的详细配置 | 秋过冬漫长 (#2) 
 
 
 
 你好，问下文章详细页的日期是怎么设置成YYYY-DD-MM这种格式的？ 
   
 &amp;mdash;

**Comment by DustReliant** [comment]
写文章我用的VS code 或者小书匠也可以的。写文章工具很多的。图片，我用了图床。------------------ 原始邮件 ------------------
发件人: "helloWorld"<notifications@github.com>
发送时间: 2020年3月14日(星期六) 晚上9:46
收件人: "chaooo/BlogComments"<BlogComments@noreply.github.com>;
抄送: "依尘"<2297024398@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [chaooo/BlogComments] 【Hexo博客折腾】BlueLake博客主题的详细配置 | 秋过冬漫长 (#2)




 顺便问下你平时是用什么写文章的，有什么图形化工具编辑文章的，还有就是平时你新插入的图片都是存到哪的，我不想用别人的图床但是不用的话本地以后文章多了可能也不太好。。 
 
 
 ------------------&nbsp;原始邮&#x4EF6;&nbsp;------------------ 
 发&#x4EF6;人:&nbsp;"我自己的邮箱"<842866986@qq.com&gt;; 
 发送时间:&nbsp;2020年3月11日(星期三) 中午1:21 
 收&#x4EF6;人:&nbsp;"chaooo/BlogComments"<reply@reply.github.com&gt;; 
 
 主题:&nbsp;回复： [chaooo/BlogComments] 【Hexo博客折腾】BlueLake博客主题的详细配置 | 秋过冬&#x6F2B;长 (#2) 
 
 
 
 可以了，谢谢，我一直在根目录的_config.yml改配置，忘记主题里面也有个配置文&#x4EF6;，刚刚一改果然可以了。 
 
 
 
 
 ------------------ 原始邮&#x4EF6; ------------------ 
 发&#x4EF6;人:&nbsp;"依尘"<notifications@github.com&gt;; 
 发送时间:&nbsp;2020年3月11日(星期三) 凌晨0:36 
 收&#x4EF6;人:&nbsp;"chaooo/BlogComments"<BlogComments@noreply.github.com&gt;; 
 抄送:&nbsp;"王壮林"<842866986@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 
 主题:&nbsp;Re: [chaooo/BlogComments] 【Hexo博客折腾】BlueLake博客主题的详细配置 | 秋过冬&#x6F2B;长 (#2) 
 
 
 
 你好，我实在主题的配置文&#x4EF6;里面设置的。里面有设置日期的格式，详细页面你改成你想要的格式即可。------------------ 原始邮&#x4EF6; ------------------  
  发&#x4EF6;人: "helloWorld"<notifications@github.com&gt;  
  发送时间: 2020年3月11日(星期三) 凌晨0:21  
  收&#x4EF6;人: "chaooo/BlogComments"<BlogComments@noreply.github.com&gt;;  
  抄送: "依尘"<2297024398@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;  
  主题: Re: [chaooo/BlogComments] 【Hexo博客折腾】BlueLake博客主题的详细配置 | 秋过冬&#x6F2B;长 (#2)  
   
   
   
  你好，问下文章详细页的日期是怎么设置成YYYY-DD-MM这种格式的？  
     
  &amp;mdash;  
  You are receiving this because you commented.  
  Reply to this email directly, view it on GitHub, or unsubscribe.  
 — 
 You are receiving this because you commented. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
&mdash;

**Comment by yzdzh** [comment]
> @1619513467
可以问下是什么图床吗？怎样插入图片会更效率点。。

**Comment by zcl1021** [comment]
为什么我的右边没有归类

**Comment by DustReliant** [comment]
开启就好了。------------------ 原始邮件 ------------------
发件人: "zcl1021"<notifications@github.com>
发送时间: 2020年3月21日(星期六) 下午5:36
收件人: "chaooo/BlogComments"<BlogComments@noreply.github.com>;
抄送: "依尘"<2297024398@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [chaooo/BlogComments] 【Hexo博客折腾】BlueLake博客主题的详细配置 | 秋过冬漫长 (#2)




 
为什么我的右边没有归类
 
&mdash;

**Comment by YueXIanHu** [comment]
感谢感谢！！

**Comment by mofan001** [comment]
Unhandled rejection TypeError: /Users/Documents/HexoBlog/themes/BlueLake/layout/archive.jade:9
7|     .post-archive
8|       .archive-wrap
> 9|         each posts, year in _.groupBy(page.posts.toArray(), function(p){return -p.date.format('YYYY')})
10|           h2= -year
11|           ul.listing
12|             for post in posts

Cannot read property 'groupBy' of undefined
    at eval (eval at exports.compile (/Users/Documents/HexoBlog/node_modules/jade/lib/index.js:218:8), <anonymous>:461:17)
    at eval (eval at exports.compile (/Users/Documents/HexoBlog/node_modules/jade/lib/index.js:218:8), <anonymous>:697:4)
    at eval (eval at exports.compile (/Users/Documents/HexoBlog/node_modules/jade/lib/index.js:218:8), <anonymous>:1215:22)
    at res (/Users/Documents/HexoBlog/node_modules/jade/lib/index.js:219:38)
    at _View._compiled.locals [as _compiled] (/Users/Documents/HexoBlog/node_modules/hexo/lib/theme/view.js:136:50)
    at _View.render (/Users/Documents/HexoBlog/node_modules/hexo/lib/theme/view.js:39:17)
    at /Users/Documents/HexoBlog/node_modules/hexo/lib/hexo/index.js:64:21
    at tryCatcher (/Users/Documents/HexoBlog/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/Documents/HexoBlog/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/Users/Documents/HexoBlog/node_modules/hexo/lib/hexo/router.js:47:5)
    at RouteStream.Readable.read (_stream_readable.js:457:10)
    at resume_ (_stream_readable.js:933:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)

我按照文档做完后，归档的功能报错，这个怎么破啊

**Comment by DustReliant** [comment]
> @felixhe01
> Unhandled rejection TypeError: /Users/Documents/HexoBlog/themes/BlueLake/layout/archive.jade:9
> 7|     .post-archive
> 8|       .archive-wrap
> > 9|         each posts, year in _.groupBy(page.posts.toArray(), function(p){return -p.date.format('YYYY')})
> 10|           h2= -year
> 11|           ul.listing
> 12|             for post in posts
> 
> Cannot read property 'groupBy' of undefined
>     at eval (eval at exports.compile (/Users/Documents/HexoBlog/node_modules/jade/lib/index.js:218:8), <anonymous>:461:17)
>     at eval (eval at exports.compile (/Users/Documents/HexoBlog/node_modules/jade/lib/index.js:218:8), <anonymous>:697:4)
>     at eval (eval at exports.compile (/Users/Documents/HexoBlog/node_modules/jade/lib/index.js:218:8), <anonymous>:1215:22)
>     at res (/Users/Documents/HexoBlog/node_modules/jade/lib/index.js:219:38)
>     at _View._compiled.locals [as _compiled] (/Users/Documents/HexoBlog/node_modules/hexo/lib/theme/view.js:136:50)
>     at _View.render (/Users/Documents/HexoBlog/node_modules/hexo/lib/theme/view.js:39:17)
>     at /Users/Documents/HexoBlog/node_modules/hexo/lib/hexo/index.js:64:21
>     at tryCatcher (/Users/Documents/HexoBlog/node_modules/bluebird/js/release/util.js:16:23)
>     at /Users/Documents/HexoBlog/node_modules/bluebird/js/release/method.js:15:34
>     at RouteStream._read (/Users/Documents/HexoBlog/node_modules/hexo/lib/hexo/router.js:47:5)
>     at RouteStream.Readable.read (_stream_readable.js:457:10)
>     at resume_ (_stream_readable.js:933:12)
>     at process.internalTickCallback (internal/process/next_tick.js:72:19)
> 
> 我按照文档做完后，归档的功能报错，这个怎么破啊




你打开你的主题目录下的layout目录下的archive.jade文件 第九行的报错。大概可能和你的缩进有关系。你自己调试一下。

**Comment by yunxiao608** [comment]
> @felixhe01
> Unhandled rejection TypeError: /Users/Documents/HexoBlog/themes/BlueLake/layout/archive.jade:9
> 7|     .post-archive
> 8|       .archive-wrap
> > 9|         each posts, year in _.groupBy(page.posts.toArray(), function(p){return -p.date.format('YYYY')})
> 10|           h2= -year
> 11|           ul.listing
> 12|             for post in posts
> 
> Cannot read property 'groupBy' of undefined
>     at eval (eval at exports.compile (/Users/Documents/HexoBlog/node_modules/jade/lib/index.js:218:8), <anonymous>:461:17)
>     at eval (eval at exports.compile (/Users/Documents/HexoBlog/node_modules/jade/lib/index.js:218:8), <anonymous>:697:4)
>     at eval (eval at exports.compile (/Users/Documents/HexoBlog/node_modules/jade/lib/index.js:218:8), <anonymous>:1215:22)
>     at res (/Users/Documents/HexoBlog/node_modules/jade/lib/index.js:219:38)
>     at _View._compiled.locals [as _compiled] (/Users/Documents/HexoBlog/node_modules/hexo/lib/theme/view.js:136:50)
>     at _View.render (/Users/Documents/HexoBlog/node_modules/hexo/lib/theme/view.js:39:17)
>     at /Users/Documents/HexoBlog/node_modules/hexo/lib/hexo/index.js:64:21
>     at tryCatcher (/Users/Documents/HexoBlog/node_modules/bluebird/js/release/util.js:16:23)
>     at /Users/Documents/HexoBlog/node_modules/bluebird/js/release/method.js:15:34
>     at RouteStream._read (/Users/Documents/HexoBlog/node_modules/hexo/lib/hexo/router.js:47:5)
>     at RouteStream.Readable.read (_stream_readable.js:457:10)
>     at resume_ (_stream_readable.js:933:12)
>     at process.internalTickCallback (internal/process/next_tick.js:72:19)
> 
> 我按照文档做完后，归档的功能报错，这个怎么破啊

我也是这个问题！！！有解决办法没

**Comment by yunxiao608** [comment]
> @1619513467
> ERROR F:\hexo\hexo\themes\BlueLake\layout\post.jade:14
>     12|         +comment-count(page.path)
>     13|       p
>   > 14|         span.date= page.date.format(theme.date_formats.post)
>     15|         if page.categories.length > 0
>     16|           span
>     17|             for category in page.categories.toArray()
> 
> Cannot read property 'post' of undefined
> TypeError: F:\hexo\hexo\themes\BlueLake\layout\post.jade:14
>     12|         +comment-count(page.path)
>     13|       p
>   > 14|         span.date= page.date.format(theme.date_formats.post)
>     15|         if page.categories.length > 0
>     16|           span
>     17|             for category in page.categories.toArray()
> 
> Cannot read property 'post' of undefined
>     at eval (eval at exports.compile (F:\hexo\hexo\node_modules\jade\lib\index.js:218:8), <anonymous>:713:108)
>     at eval (eval at exports.compile (F:\hexo\hexo\node_modules\jade\lib\index.js:218:8), <anonymous>:2582:22)
>     at res (F:\hexo\hexo\node_modules\jade\lib\index.js:219:38)
>     at Theme._View.View._compiled (F:\hexo\hexo\node_modules\hexo\lib\theme\view.js:123:48)
>     at Theme._View.View.View.render (F:\hexo\hexo\node_modules\hexo\lib\theme\view.js:29:15)
>     at F:\hexo\hexo\node_modules\hexo\lib\hexo\index.js:349:21
>     at tryCatcher (F:\hexo\hexo\node_modules\bluebird\js\release\util.js:16:23)
>     at F:\hexo\hexo\node_modules\bluebird\js\release\method.js:15:34
>     at RouteStream._read (F:\hexo\hexo\node_modules\hexo\lib\hexo\router.js:123:3)
>     at RouteStream.Readable.read (_stream_readable.js:491:10)
> 
> 
> 
> 这个报错这怎么回事？
> 

请问这个是怎么解决的，我也遇到了。。。

**Comment by 60ke** [comment]
你好，请问博客首页的文章显示长度怎么设置(不用文章中添加more的方式)

**Comment by 60ke** [comment]
知道了可以用`hexo-excerpt`这个插件

**Comment by dhndzwxj** [comment]
代码块的复制功能怎么添加啊？

**Comment by hokbam** [comment]
你好，为什么我首页的文章都是完全展开的呢？怎么设置像你的一样，只展开固定行数？

**Comment by dhndzwxj** [comment]
我们的主题都不太一样，没法指导呀


Xiaojun Wang
13718899506
Department of Economy
Renmin University of China




---- 回复的原邮件 ----
发件人 ***@***.***>日期 2022年08月30日 17:41收件人 ***@***.***>抄送至 Junker ***@***.******@***.***>主题 Re: [chaooo/BlogComments] BlueLake博客主题的详细配置 | 秋过冬漫长 (#2)

你好，为什么我首页的文章都是完全展开的呢？怎么设置像你的一样，只展开固定行数？

**Comment by chaooo** [comment]
> @hokbam
> 你好，为什么我首页的文章都是完全展开的呢？怎么设置像你的一样，只展开固定行数？

通过添加`<!-- more -->`标记手动切割文章，或者通过插件抓取摘要

**Comment by chaooo** [comment]
> @dhndzwxj
> 代码块的复制功能怎么添加啊？

通过插件可以实现，试试`clipboard.js`呢
